#!/bin/bash

# SquashTrainingApp 프로젝트 자동화 시작 스크립트
# 5개 터미널 생성 후 프로젝트 실행

echo "🎯 SquashTrainingApp 프로젝트 자동화 시작"
echo "=================================================="
echo ""

# 1. 터미널 생성
echo "1단계: 터미널 생성 중..."
/mnt/c/Git/Routine_app/RUN-WSL-CLAUDE-AUTOMATION.sh

echo ""
echo "2단계: 프로젝트 실행 시작..."
echo ""

# 프로젝트 디렉토리로 이동
cd /mnt/c/Git/Routine_app/SquashTrainingApp

echo "현재 디렉토리: $(pwd)"
echo ""

# 프로젝트 상태 확인
echo "📋 프로젝트 상태 확인:"
echo "- package.json 존재: $([ -f package.json ] && echo '✅' || echo '❌')"
echo "- android 디렉토리 존재: $([ -d android ] && echo '✅' || echo '❌')"
echo "- node_modules 존재: $([ -d node_modules ] && echo '✅' || echo '❌')"
echo ""

# 각 터미널에서 실행할 초기 작업 정의
echo "=================================================="
echo "🧠 플래너 터미널에서 실행할 초기 작업:"
echo "=================================================="
echo ""
echo "cd /mnt/c/Git/Routine_app/SquashTrainingApp"
echo "claude --model claude-3-opus-20240229"
echo ""
echo "Then in Claude Code:"
echo "\"\"\"
echo "안녕하세요! 저는 🧠 Claude4-Opus-Planner입니다."
echo "SquashTrainingApp 프로젝트의 계획 및 아키텍처 설계를 담당합니다."
echo ""
echo "현재 프로젝트 상태를 분석하고 50+ 사이클 자동화 계획을 수립하겠습니다."
echo ""
echo "먼저 프로젝트 구조를 파악해주세요:"
echo "1. 현재 코드 상태 분석"
echo "2. 빌드 가능 상태 확인"
echo "3. 테스트 환경 점검"
echo "4. 다음 개발 단계 계획"
echo ""
echo "다른 터미널의 코더들에게 작업을 분배하겠습니다."
echo "\"\"\""
echo ""

echo "=================================================="
echo "🔨 주요 코더 터미널에서 실행할 초기 작업:"
echo "=================================================="
echo ""
echo "cd /mnt/c/Git/Routine_app/SquashTrainingApp"
echo "claude --model claude-3-5-sonnet-20241022"
echo ""
echo "Then in Claude Code:"
echo "\"\"\"
echo "안녕하세요! 저는 🔨 Claude4-Sonnet-Coder1입니다."
echo "SquashTrainingApp 프로젝트의 주요 코드 구현을 담당합니다."
echo ""
echo "현재 작업 대기 중입니다. 플래너의 지시에 따라:"
echo "1. React Native 컴포넌트 구현"
echo "2. 핵심 비즈니스 로직 작성"
echo "3. 상태 관리 및 API 연동"
echo "4. TypeScript 타입 정의"
echo ""
echo "플래너가 작업을 할당하면 즉시 구현을 시작하겠습니다."
echo "\"\"\""
echo ""

echo "=================================================="
echo "🔧 테스트 코더 터미널에서 실행할 초기 작업:"
echo "=================================================="
echo ""
echo "cd /mnt/c/Git/Routine_app/SquashTrainingApp"
echo "claude --model claude-3-5-sonnet-20241022"
echo ""
echo "Then in Claude Code:"
echo "\"\"\"
echo "안녕하세요! 저는 🔧 Claude4-Sonnet-Coder2입니다."
echo "SquashTrainingApp 프로젝트의 테스트 및 디버깅을 담당합니다."
echo ""
echo "현재 작업 대기 중입니다. 다음 작업을 준비하고 있습니다:"
echo "1. 빌드 테스트 및 디버깅"
echo "2. 기능 테스트 수행"
echo "3. 버그 수정 및 최적화"
echo "4. 품질 보증 및 검증"
echo ""
echo "코더1이 구현을 완료하면 즉시 테스트를 시작하겠습니다."
echo "\"\"\""
echo ""

echo "=================================================="
echo "⚙️ 빌드 코더 터미널에서 실행할 초기 작업:"
echo "=================================================="
echo ""
echo "cd /mnt/c/Git/Routine_app/SquashTrainingApp"
echo "claude --model claude-3-5-sonnet-20241022"
echo ""
echo "Then in Claude Code:"
echo "\"\"\"
echo "안녕하세요! 저는 ⚙️ Claude4-Sonnet-Coder3입니다."
echo "SquashTrainingApp 프로젝트의 빌드 및 배포를 담당합니다."
echo ""
echo "현재 작업 대기 중입니다. 다음 작업을 준비하고 있습니다:"
echo "1. APK 빌드 및 배포"
echo "2. 에뮬레이터 테스트"
echo "3. 설치/삭제 사이클 관리"
echo "4. 배포 스크립트 최적화"
echo ""
echo "테스트가 완료되면 즉시 빌드 및 배포를 시작하겠습니다."
echo "\"\"\""
echo ""

echo "=================================================="
echo "📊 모니터 터미널에서 실행할 초기 작업:"
echo "=================================================="
echo ""
echo "cd /mnt/c/Git/Routine_app/SquashTrainingApp"
echo "claude --model claude-3-5-sonnet-20241022"
echo ""
echo "Then in Claude Code:"
echo "\"\"\"
echo "안녕하세요! 저는 📊 Claude4-Sonnet-Monitor입니다."
echo "SquashTrainingApp 프로젝트의 모니터링 및 조정을 담당합니다."
echo ""
echo "현재 전체 팀 상황을 모니터링하고 있습니다:"
echo "1. 전체 진행 상황 모니터링"
echo "2. 팀 간 조정 및 협업"
echo "3. 성과 측정 및 리포팅"
echo "4. 50+ 사이클 진행 상황 추적"
echo ""
echo "모든 팀원의 작업을 조정하고 최적화하겠습니다."
echo "\"\"\""
echo ""

echo "=================================================="
echo "🎯 50+ 사이클 자동화 진행 절차"
echo "=================================================="
echo ""
echo "각 사이클마다 다음 순서로 진행하세요:"
echo ""
echo "1. 🧠 플래너: 해당 사이클의 목표와 계획 수립"
echo "2. 🔨 코더1: 플래너의 지시에 따라 기능 구현"
echo "3. 🔧 코더2: 구현된 기능의 테스트 및 디버깅"
echo "4. ⚙️ 코더3: 테스트 완료 후 빌드 및 배포"
echo "5. 📊 모니터: 전체 사이클 결과 분석 및 다음 사이클 준비"
echo ""
echo "각 사이클에서 다음을 수행:"
echo "• 설치 → 실행 → 모든 기능 디버그 → 앱 삭제 → 수정"
echo "• fail/issue가 없을 때까지 반복"
echo "• 50회 이상 반복 수행"
echo ""
echo "=================================================="
echo "🚀 이제 각 터미널에서 Claude Code를 시작하세요!"
echo "=================================================="
echo ""
echo "성공적인 자동화를 위해 화이팅! 🎯"